### ISSUE TITLE
.topmsg not reverted

### ISSUE THREAD

**Issue by greenrd** [magit/magit-topgit#2]
I was in a topic branch, and I created a new topgit branch using magit-topgit. `.topmsg` was not auto-reverted, contrary to how magit behaves, so I had to press a key in it and choose `r` to revert.

**Comment by tarsius** [comment]
Is that file checked into Git? If not, then this expected, because only tracked files are reverted by default.

**Comment by greenrd** [comment]
It is checked in in the old branch, but not in the new branch. I guess that explains it.

**Comment by tarsius** [comment]
Yes ;-)
