### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by tarsius** [magit/magit-topgit#5]
I don't use `topgit`, never have. So I am not the ideal person to maintain this and am looking for a volunteer to take over.

/cc @wilx @greenrd

**Comment by greenrd** [comment]
OK, I'll take it, since I am the (dormant) maintainer of TopGit!

**Comment by tarsius** [comment]
Thanks a lot! And good luck.

Your first act as maintainer should be to update the library header :-)
