### ISSUE TITLE
or: Wrong type argument: magit-section, (topgit-topic topgit-topics status)

### ISSUE THREAD

**Issue by greenrd** [magit/magit-topgit#9]
when pressing Enter on a topic in magit-status.

Started happening today with the latest magit from melpa.

**Comment by tarsius** [comment]
Try replacing `(magit-section-when topgit-topic)` with `(magit-section-match 'topgit-topic)`.

**Comment by tarsius** [comment]
If you provide a backtrace, then I can look into it.

**Comment by tarsius** [comment]
Actually, I think recompiling `magit-topgit.el` should fix it.

**Comment by greenrd** [comment]
Recompiling `magit-topgit.el` worked... the second time I tried it, but not the first time. Weird!
